repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, "from __future__ import annotations"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML", "types-python-dateutil"]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.2"]
        language_version: python3.10
        args: [--skip-string-normalization]
